In [2]:
pip install pandas numpy matplotlib seaborn scikit-learn xgboost ucimlrepo

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

Load dataset

In [3]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
diabetes_130_us_hospitals_for_years_1999_2008 = fetch_ucirepo(id=296)

# data (as pandas dataframes)
X = diabetes_130_us_hospitals_for_years_1999_2008.data.features
y = diabetes_130_us_hospitals_for_years_1999_2008.data.targets

# metadata
print(diabetes_130_us_hospitals_for_years_1999_2008.metadata)

# variable information
print(diabetes_130_us_hospitals_for_years_1999_2008.variables)

/usr/local/lib/python3.12/dist-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

{'uci_id': 296, 'name': 'Diabetes 130-US Hospitals for Years 1999-2008', 'repository_url': 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008', 'data_url': 'https://archive.ics.uci.edu/static/public/296/data.csv', 'abstract': 'The dataset represents ten years (1999-2008) of clinical care at 130 US hospitals and integrated delivery networks. Each row concerns hospital records of patients diagnosed with diabetes, who underwent laboratory, medications, and stayed up to 14 days. The goal is to determine the early readmission of the patient within 30 days of discharge.\nThe problem is important for the following reasons. Despite high-quality evidence showing improved clinical outcomes for diabetic patients who receive various preventive and therapeutic interventions, many patients do not receive them. This can be partially attributed to arbitrary diabetes management in hospital environments, which fail to attend to glycemic control. Failure to provide proper diabetes care not only increases the managing costs for the hospitals (as the patients are readmitted) but also impacts the morbidity and mortality of the patients, who may face complications associated with diabetes.\n', 'area': 'Health and Medicine', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 101766, 'num_features': 47, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Race', 'Gender', 'Age'], 'target_col': ['readmitted'], 'index_col': ['encounter_id', 'patient_nbr'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5230J', 'creators': ['John Clore', 'Krzysztof Cios', 'Jon DeShazo', 'Beata Strack'], 'intro_paper': {'ID': 225, 'type': 'NATIVE', 'title': 'Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Record', 'authors': 'Beata Strack, Jonathan DeShazo, Chris Gennings, Juan Olmo, Sebastian Ventura, Krzysztof Cios, John Clore', 'venue': 'BioMed Research International, vol. 2014', 'year': 2014, 'journal': None, 'DOI': None, 'URL': 'https://www.hindawi.com/journals/bmri/2014/781670/', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'The dataset represents ten years (1999-2008) of clinical care at 130 US hospitals and integrated delivery networks. It includes over 50 features representing patient and hospital outcomes. Information was extracted from the database for encounters that satisfied the following criteria.\n(1)\tIt is an inpatient encounter (a hospital admission).\n(2)\tIt is a diabetic encounter, that is, one during which any kind of diabetes was entered into the system as a diagnosis.\n(3)\tThe length of stay was at least 1 day and at most 14 days.\n(4)\tLaboratory tests were performed during the encounter.\n(5)\tMedications were administered during the encounter.\n\nThe data contains such attributes as patient number, race, gender, age, admission type, time in hospital, medical specialty of admitting physician, number of lab tests performed, HbA1c test result, diagnosis, number of medications, diabetic medications, number of outpatient, inpatient, and emergency visits in the year before the hospitalization, etc.', 'purpose': None, 'funded_by': None, 'instances_represent': 'The instances represent hospitalized patient records diagnosed with diabetes.', 'recommended_data_splits': 'No recommendation. The standard train-test split could be used. Can use three-way holdout split (i.e., train-validation-test) when doing model selection.', 'sensitive_data': 'Yes. The dataset contains information about the age, gender, and race of the patients.', 'preprocessing_description': None, 'variable_info': 'Detailed description of all the atrributes is provided in Table 1 Beata Strack, Jonathan P. DeShazo, Chris Gennings,  Juan L. Olmo, Sebastian Ventura,  Krzysztof J. Cios, and John N. Clore, “Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records,” BioMed Research International, vol. 2014, Article ID 781670, 11 pages, 2014.\n\nhttp://www.hindawi.com/journals/bmri/2014/781670/', 'citation': 'Please cite:\nBeata Strack, Jonathan P. DeShazo, Chris Gennings, Juan L. Olmo, Sebastian Ventura, Krzysztof J. Cios, and John N. Clore, “Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records,” BioMed Research International, vol. 2014, Article ID 781670, 11 pages, 2014.'}}
                        name     role         type demographic  \
0               encounter_id       ID                     None
1                patient_nbr       ID                     None
2                       race  Feature  Categorical        Race
3                     gender  Feature  Categorical      Gender
4                        age  Feature  Categorical         Age
5                     weight  Feature  Categorical        None
6          admission_type_id  Feature  Categorical        None
7   discharge_disposition_id  Feature  Categorical        None
8        admission_source_id  Feature  Categorical        None
9           time_in_hospital  Feature      Integer        None
10                payer_code  Feature  Categorical        None
11         medical_specialty  Feature  Categorical        None
12        num_lab_procedures  Feature      Integer        None
13            num_procedures  Feature      Integer        None
14           num_medications  Feature      Integer        None
15         number_outpatient  Feature      Integer        None
16          number_emergency  Feature      Integer        None
17          number_inpatient  Feature      Integer        None
18                    diag_1  Feature  Categorical        None
19                    diag_2  Feature  Categorical        None
20                    diag_3  Feature  Categorical        None
21          number_diagnoses  Feature      Integer        None
22             max_glu_serum  Feature  Categorical        None
23                 A1Cresult  Feature  Categorical        None
24                 metformin  Feature  Categorical        None
25               repaglinide  Feature  Categorical        None
26               nateglinide  Feature  Categorical        None
27            chlorpropamide  Feature  Categorical        None
28               glimepiride  Feature  Categorical        None
29             acetohexamide  Feature  Categorical        None
30                 glipizide  Feature  Categorical        None
31                 glyburide  Feature  Categorical        None
32               tolbutamide  Feature  Categorical        None
33              pioglitazone  Feature  Categorical        None
34             rosiglitazone  Feature  Categorical        None
35                  acarbose  Feature  Categorical        None
36                  miglitol  Feature  Categorical        None
37              troglitazone  Feature  Categorical        None
38                tolazamide  Feature  Categorical        None
39                   examide  Feature  Categorical        None
40               citoglipton  Feature  Categorical        None
41                   insulin  Feature  Categorical        None
42       glyburide-metformin  Feature  Categorical        None
43       glipizide-metformin  Feature  Categorical        None
44  glimepiride-pioglitazone  Feature  Categorical        None
45   metformin-rosiglitazone  Feature  Categorical        None
46    metformin-pioglitazone  Feature  Categorical        None
47                    change  Feature  Categorical        None
48               diabetesMed  Feature  Categorical        None
49                readmitted   Target  Categorical        None

                                          description units missing_values
0                   Unique identifier of an encounter  None             no
1                      Unique identifier of a patient  None             no
2   Values: Caucasian, Asian, African American, Hi...  None            yes
3           Values: male, female, and unknown/invalid  None             no
4   Grouped in 10-year intervals: [0, 10), [10, 20...  None             no
5                                   Weight in pounds.  None            yes
6   Integer identifier corresponding to 9 distinct...  None             no
7   Integer identifier corresponding to 29 distinc...  None             no
8   Integer identifier corresponding to 21 distinc...  None             no
9   Integer number of days between admission and d...  None             no
10  Integer identifier corresponding to 23 distinc...  None            yes
11  Integer identifier of a specialty of the admit...  None            yes
12  Number of lab tests performed during the encou...  None             no
13  Number of procedures (other than lab tests) pe...  None             no
14  Number of distinct generic names administered ...  None             no
15  Number of outpatient visits of the patient in ...  None             no
16  Number of emergency visits of the patient in t...  None             no
17  Number of inpatient visits of the patient in t...  None             no
18  The primary diagnosis (coded as first three di...  None            yes
19  Secondary diagnosis (coded as first three digi...  None            yes
20  Additional secondary diagnosis (coded as first...  None            yes
21          Number of diagnoses entered to the system  None             no
22  Indicates the range of the result or if the te...  None             no
23  Indicates the range of the result or if the te...  None             no
24  The feature indicates whether the drug was pre...  None             no
25  The feature indicates whether the drug was pre...  None             no
26  The feature indicates whether the drug was pre...  None             no
27  The feature indicates whether the drug was pre...  None             no
28  The feature indicates whether the drug was pre...  None             no
29  The feature indicates whether the drug was pre...  None             no
30  The feature indicates whether the drug was pre...  None             no
31  The feature indicates whether the drug was pre...  None             no
32  The feature indicates whether the drug was pre...  None             no
33  The feature indicates whether the drug was pre...  None             no
34  The feature indicates whether the drug was pre...  None             no
35  The feature indicates whether the drug was pre...  None             no
36  The feature indicates whether the drug was pre...  None             no
37  The feature indicates whether the drug was pre...  None             no
38  The feature indicates whether the drug was pre...  None             no
39  The feature indicates whether the drug was pre...  None             no
40  The feature indicates whether the drug was pre...  None             no
41  The feature indicates whether the drug was pre...  None             no
42  The feature indicates whether the drug was pre...  None             no
43  The feature indicates whether the drug was pre...  None             no
44  The feature indicates whether the drug was pre...  None             no
45  The feature indicates whether the drug was pre...  None             no
46  The feature indicates whether the drug was pre...  None             no
47  Indicates if there was a change in diabetic me...  None             no
48  Indicates if there was any diabetic medication...  None             no
49  Days to inpatient readmission. Values: <30 if ...  None             no

In [4]:
from ucimlrepo import fetch_ucirepo

data = fetch_ucirepo(id=296)

df = data.data.features
target = data.data.targets

/usr/local/lib/python3.12/dist-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

In [5]:
df['readmitted'] = target

/tmp/ipython-input-772989973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['readmitted'] = target

EDA Part 1

In [6]:
df.shape

(101766, 48)

In [7]:
df.head()

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,...,No,No,No,No,No,No,No,No,No,NO
1,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,...,No,No,No,No,No,No,No,No,Yes,NO
3,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   race                      99493 non-null   object
 1   gender                    101766 non-null  object
 2   age                       101766 non-null  object
 3   weight                    3197 non-null    object
 4   admission_type_id         101766 non-null  int64
 5   discharge_disposition_id  101766 non-null  int64
 6   admission_source_id       101766 non-null  int64
 7   time_in_hospital          101766 non-null  int64
 8   payer_code                61510 non-null   object
 9   medical_specialty         51817 non-null   object
 10  num_lab_procedures        101766 non-null  int64
 11  num_procedures            101766 non-null  int64
 12  num_medications           101766 non-null  int64
 13  number_outpatient         101766 non-null  int64
 14  number_emergency          101766 non-null  int64
 15  number_inpatient          101766 non-null  int64
 16  diag_1                    101745 non-null  object
 17  diag_2                    101408 non-null  object
 18  diag_3                    100343 non-null  object
 19  number_diagnoses          101766 non-null  int64
 20  max_glu_serum             5346 non-null    object
 21  A1Cresult                 17018 non-null   object
 22  metformin                 101766 non-null  object
 23  repaglinide               101766 non-null  object
 24  nateglinide               101766 non-null  object
 25  chlorpropamide            101766 non-null  object
 26  glimepiride               101766 non-null  object
 27  acetohexamide             101766 non-null  object
 28  glipizide                 101766 non-null  object
 29  glyburide                 101766 non-null  object
 30  tolbutamide               101766 non-null  object
 31  pioglitazone              101766 non-null  object
 32  rosiglitazone             101766 non-null  object
 33  acarbose                  101766 non-null  object
 34  miglitol                  101766 non-null  object
 35  troglitazone              101766 non-null  object
 36  tolazamide                101766 non-null  object
 37  examide                   101766 non-null  object
 38  citoglipton               101766 non-null  object
 39  insulin                   101766 non-null  object
 40  glyburide-metformin       101766 non-null  object
 41  glipizide-metformin       101766 non-null  object
 42  glimepiride-pioglitazone  101766 non-null  object
 43  metformin-rosiglitazone   101766 non-null  object
 44  metformin-pioglitazone    101766 non-null  object
 45  change                    101766 non-null  object
 46  diabetesMed               101766 non-null  object
 47  readmitted                101766 non-null  object
dtypes: int64(11), object(37)
memory usage: 37.3+ MB

In [9]:
df.describe()

,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [10]:
df.isnull().sum()

race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

Target Variable Analysis

In [11]:
df['readmitted'].value_counts()
df['readmitted'].value_counts(normalize=True)

readmitted
NO     0.539119
>30    0.349282
<30    0.111599
Name: proportion, dtype: float64

In [12]:
df['readmitted_binary'] = df['readmitted'].apply(lambda x: 1 if x == '<30' else 0)

df['readmitted_binary'].value_counts(normalize=True)

/tmp/ipython-input-2398817555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['readmitted_binary'] = df['readmitted'].apply(lambda x: 1 if x == '<30' else 0)

readmitted_binary
0    0.888401
1    0.111599
Name: proportion, dtype: float64

In [13]:
df.loc[:, 'readmitted_binary'] = df['readmitted'].apply(lambda x: 1 if x == '<30' else 0)

Drop high-missing columns

In [14]:

df = df.drop(columns=[
    'weight',
    'payer_code',
    'medical_specialty',
    'max_glu_serum',
    'A1Cresult'
])

Drop IDs (no predictive value)

In [15]:
df = df.drop(columns=[
    'encounter_id',
    'patient_nbr'
], errors='ignore')

In [16]:
df.isnull().sum().sort_values(ascending=False).head(10)

race                        2273
diag_3                      1423
diag_2                       358
diag_1                        21
discharge_disposition_id       0
admission_source_id            0
time_in_hospital               0
num_lab_procedures             0
num_procedures                 0
gender                         0
dtype: int64

Handle Missing Values Properly

In [17]:
df['race'] = df['race'].fillna('Unknown')

In [18]:
df['diag_1'] = df['diag_1'].fillna('Unknown')
df['diag_2'] = df['diag_2'].fillna('Unknown')
df['diag_3'] = df['diag_3'].fillna('Unknown')

In [19]:
df.isnull().sum().sum()

np.int64(0)

FEATURE ENGINEERING

In [20]:
df['total_visits'] = (
    df['number_outpatient'] +
    df['number_emergency'] +
    df['number_inpatient']
)

Medication intensity

In [21]:
df['medication_intensity'] = df['num_medications']

Procedure intensity

In [22]:
df['procedure_intensity'] = df['num_procedures']

Lab intensity

In [23]:
df['lab_intensity'] = df['num_lab_procedures']

Exploratory Data Analysis

Age vs Readmission

In [24]:
df.groupby('age')['readmitted_binary'].mean().sort_index()

age
[0-10)      0.018634
[10-20)     0.057887
[20-30)     0.142426
[30-40)     0.112318
[40-50)     0.106040
[50-60)     0.096662
[60-70)     0.111284
[70-80)     0.117731
[80-90)     0.120835
[90-100)    0.110992
Name: readmitted_binary, dtype: float64

In [25]:

df.groupby('time_in_hospital')['readmitted_binary'].mean()

time_in_hospital
1     0.081785
2     0.099396
3     0.106668
4     0.118070
5     0.120309
6     0.125879
7     0.128350
8     0.142337
9     0.137242
10    0.143467
11    0.105121
12    0.133287
13    0.123140
14    0.129559
Name: readmitted_binary, dtype: float64

In [26]:
df.groupby('total_visits')['readmitted_binary'].mean().head(20)

total_visits
0     0.081751
1     0.115641
2     0.146194
3     0.152778
4     0.171148
5     0.183694
6     0.232292
7     0.226959
8     0.245487
9     0.274419
10    0.244444
11    0.302419
12    0.264706
13    0.295918
14    0.379310
15    0.329897
16    0.308824
17    0.333333
18    0.343750
19    0.468750
Name: readmitted_binary, dtype: float64

In [27]:
df.groupby('insulin')['readmitted_binary'].mean()

insulin
Down      0.138975
No        0.100374
Steady    0.111284
Up        0.129905
Name: readmitted_binary, dtype: float64

Patients not on insulin

Lowest readmission risk (~10%)

Likely milder diabetes cases

Dose change (Up / Down)

Higher risk (13–14%)

Indicates unstable glucose control

Steady insulin

Moderate risk

Managed but chronic condition

DATA PREPARATION FOR MODEL

In [28]:
df = df.drop(columns=['readmitted'])

Separate features (X) and target (y)

In [29]:
X = df.drop(columns=['readmitted_binary'])
y = df['readmitted_binary']

Convert categorical → numeric (Encoding)

In [30]:
import pandas as pd

X = pd.get_dummies(X, drop_first=True)

Check feature count

In [31]:
X.shape

(101766, 2334)

TRAIN TEST SPLIT

Split dataset

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

Check sizes

In [33]:
print(X_train.shape)
print(X_test.shape)

(81412, 2334)
(20354, 2334)

FIRST MODEL (Logistic Regression)

Train Logistic Regression

In [34]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

Predict

In [35]:
y_pred = model.predict(X_test)

Evaluate

In [36]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18035    48]
 [ 2222    49]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     18083
           1       0.51      0.02      0.04      2271

    accuracy                           0.89     20354
   macro avg       0.70      0.51      0.49     20354
weighted avg       0.85      0.89      0.84     20354

Train Logistic Regression

In [37]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

Make predictions on test data

In [38]:
y_pred = model.predict(X_test)

Evaluate model

In [39]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18035    48]
 [ 2222    49]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     18083
           1       0.51      0.02      0.04      2271

    accuracy                           0.89     20354
   macro avg       0.70      0.51      0.49     20354
weighted avg       0.85      0.89      0.84     20354

Train weighted logistic regression

In [41]:
from sklearn.linear_model import LogisticRegression

model_weighted = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

model_weighted.fit(X_train, y_train)

y_pred_weighted = model_weighted.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred_weighted))
print(classification_report(y_test, y_pred_weighted))

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[[11844  6239]
 [ 1026  1245]]
              precision    recall  f1-score   support

           0       0.92      0.65      0.77     18083
           1       0.17      0.55      0.26      2271

    accuracy                           0.64     20354
   macro avg       0.54      0.60      0.51     20354
weighted avg       0.84      0.64      0.71     20354

SMOTE

In [44]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [45]:
y_train_smote.value_counts()

readmitted_binary
0    72326
1    72326
Name: count, dtype: int64

Train Random Forest on SMOTE Data

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

rf_smote = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_smote.fit(X_train_smote, y_train_smote)

y_pred_rf_smote = rf_smote.predict(X_test)

print(confusion_matrix(y_test, y_pred_rf_smote))
print(classification_report(y_test, y_pred_rf_smote))

[[17953   130]
 [ 2207    64]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94     18083
           1       0.33      0.03      0.05      2271

    accuracy                           0.89     20354
   macro avg       0.61      0.51      0.50     20354
weighted avg       0.83      0.89      0.84     20354

In [47]:
 import pandas as pd

feature_importance = pd.Series(
    rf_smote.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

feature_importance.head(20)

age_[50-60)                 0.029567
insulin_No                  0.029274
age_[60-70)                 0.027263
lab_intensity               0.025625
num_lab_procedures          0.025620
age_[70-80)                 0.025363
insulin_Steady              0.024897
medication_intensity        0.023244
num_medications             0.023076
change_No                   0.021522
metformin_Steady            0.020440
age_[80-90)                 0.019475
time_in_hospital            0.019228
age_[40-50)                 0.018934
gender_Male                 0.017434
discharge_disposition_id    0.017013
diag_3_250                  0.016195
number_diagnoses            0.015948
insulin_Up                  0.015724
glipizide_Steady            0.014792
dtype: float64